### ISSUE TITLE
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005)

### ISSUE THREAD

**Issue by jack9684** [neo-project/neo-express#208]
when i first run a empty neo-express server it ok ,but when i close it start again ,it will never start .except i use the reset the blockchain button 
the errors  are:

Starting Neo Express...

Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
at RocksDbSharp.Iterator.Seek(System.ReadOnlySpan`1<Byte>)
at Neo.BlockchainToolkit.Persistence.Extensions.Seek(RocksDbSharp.RocksDb, RocksDbSharp.ColumnFamilyHandle, System.ReadOnlySpan`1<Byte>, Neo.Persistence.SeekDirection, RocksDbSharp.ReadOptions)
at Neo.BlockchainToolkit.Persistence.RocksDbStore.Seek(Byte[], Neo.Persistence.SeekDirection)
at Neo.Persistence.SnapshotCache.SeekInternal(Byte[], Neo.Persistence.SeekDirection)
                                                           at Neo.Persistence.DataCache+<Seek>d__19.MoveNext()
at Neo.Persistence.DataCache+<Find>d__11.MoveNext()
at System.Linq.Enumerable.Any[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.ValueTuple`2<System.__Canon,System.__Canon>>)
at Neo.SmartContract.Native.LedgerContract.Initialized(Neo.Persistence.DataCache)
at Neo.Ledger.Blockchain.OnInitialize()
at Akka.Actor.UntypedActor.Receive(System.Object)
                                                    at Akka.Actor.ActorBase.AroundReceive(Akka.Actor.Receive, System.Object)
at Akka.Actor.ActorCell.ReceiveMessage(System.Object)
    at Akka.Actor.ActorCell.Invoke(Akka.Actor.Envelope)
at Akka.Dispatch.Mailbox.ProcessMailbox(Int32, Int64)
    at Akka.Dispatch.Mailbox.ProcessMailbox()
                                                at Akka.Dispatch.Mailbox.<Run>b__36_0()
at Akka.Actor.ActorCell.UseThreadContext(System.Action)
      at Akka.Dispatch.Mailbox.Run()
                                       at Akka.Dispatch.ThreadPoolExecutorService+<>c.<.cctor>b__3_0(System.Object)
at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
                    at System.Threading.ThreadPoolWorkQueue.Dispatch()
                     at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()

Neo Express has exited with code 3221225501.

**Comment by jack9684** [comment]
@devhawk windows7 serverpack1（add VC_redist.x64 and Windows6.1-KB3063858-x64）   vscodeusersetup-x64-1.65.2 dotnet-sdk-6.0.200-win-x64 . should i use win10?

**Comment by jack9684** [comment]
Neo Blockchain Toolkit  v2.0.5

**Comment by devhawk** [comment]
> @devhawk windows7 serverpack1（add VC_redist.x64 and Windows6.1-KB3063858-x64） vscodeusersetup-x64-1.65.2 dotnet-sdk-6.0.200-win-x64 . should i use win10?

Win 7 is out of support. No idea if .net 6 or RocksDB works on Win 7.

**Comment by jack9684** [comment]
@devhawk 
OK，thank u . another question  when i use <deploy contract to neo  express> button to deploy contract ,there is just ask me to choose the  account ,then seclect the .nef contract，did not let me choose  the signature like the <invoke contract> button.
so when i have the code in the contract like 
 private static void throwIfSignerIsNotOwner() {
        assert Runtime.checkWitness(owner) : "The calling entity is not the owner of this contract.";
    }
 @OnDeployment
    public static void deploy(Object data, boolean update) {
        if (!update) {
            throwIfSignerIsNotOwner();
            // Initialize the supply
            int initialSupply = 200_000_000;
            Storage.put(ctx, totalSupplyKey, initialSupply);
            // Allocate all tokens to the contract owner.
            assetMap.put(owner.toByteArray(), initialSupply);
        }
    }  
Runtime.checkWitness(owner) its the function  by neow3j.  not write by myself.
 /**
     * Verifies whether the container (e.g. the transactions) calling the contract is signed by the
     * given script hash (e.g. an account).
     *
     * @param scriptHash The script hash to check.
     * @return true if the given script hash is the signer of the transaction. False, otherwise.
     */
    @Instruction(interopService = SYSTEM_RUNTIME_CHECKWITNESS)
    public static native boolean checkWitness(Hash160 scriptHash);

then delopy function  Runtime.checkWitness(owner)  means if when owner wallet address is the deploy wallet then suceess,but when i use the same wallet to <deploy contract to neo  express> it never work suceess. its failed.

but when i use <invoke contract> button to run the operation choose  the signature  ,the code include this method it works.
so how it works Runtime.checkWitness(owner) when i deploy the contract?

**Comment by devhawk** [comment]
Questions like this should be asked on the [Neo Discord](https://discord.gg/rvZFQ5382k). There's a set of #development channels where you can get support, including a java channel that the neow3j folks monitor.
