### ISSUE TITLE
Batch file with contract run with zero arguments sometimes doesn't work

### ISSUE THREAD

**Issue by luc10921** [neo-project/neo-express#279]
Trying to run a batch file with a `contract run` with zero args after another `contract run` with 1+ args results in the one with 0 args trying to use the same args as the one before.

Example 1:
```batch
transfer 1000 GAS genesis testAccount1
contract run --account testAccount1 GasToken balanceOf @testAccount1

contract run --account testAccount1 GasToken totalSupply
```
Results in: ![image](https://user-images.githubusercontent.com/49196318/233477948-fde5b543-e9fe-4635-84c5-89da30b767e5.png)

Example 2:
```batch
transfer 1000 GAS genesis testAccount1
contract run --account testAccount1 GasToken balanceOf @testAccount1
contract run --account testAccount1 GasToken transfer @testAccount1 @testAccount2 1000 "test"

contract run --account testAccount1 GasToken totalSupply
```
Results in: 
![image](https://user-images.githubusercontent.com/49196318/233478563-be4fe49c-d710-4b13-87f8-4779c7b67a63.png)

**Comment by cschuchardt88** [comment]
Ty for report. Looks like a problem with `neo` core
```
System.InvalidOperationException: Failed execution for 'wh8MCWJhbGFuY2VPZgwUz3bii9AGLEpHjuNVYQETGfPPpNJBYn1bUg=='
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Method "balanceOf" with 0 parameter(s) doesn't exist in the contract 0xd2a4cff31913016155e38e474a2c06d08be276cf.
   at Neo.SmartContract.ApplicationEngine.CallContract(UInt160 contractHash, String method, CallFlags callFlags, Array args)
   at InvokeStub_ApplicationEngine.CallContract(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Neo.SmartContract.ApplicationEngine.OnSysCall(InteropDescriptor descriptor)
   at Neo.SmartContract.ApplicationEngine.OnSysCall(UInt32 method)
   at Neo.VM.ExecutionEngine.ExecuteInstruction(Instruction instruction)
   at Neo.VM.ExecutionEngine.ExecuteNext()
   --- End of inner exception stack trace ---
```

**Comment by cschuchardt88** [comment]
After debugging its look like you just need to wrap anything has `@` sign, in quotes.

```
transfer 1000 GAS genesis testAccount1
contract run --account testAccount1 GasToken balanceOf `@testAccount1`
contract run --account testAccount1 GasToken totalSupply
```
